name: open-cwm-module1

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  plan-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
      - name: Plan Flask repo
        run: |
          python -m orchestrator.run plan --repo-id pallets_flask --workspace .open-cwm-ci
      - name: Package Flask repo
        run: |
          python -m orchestrator.run package --repo-id pallets_flask --workspace .open-cwm-ci
